name: 'Delete Old Releases'
on: [push]
jobs:
  delete_old_releases:
    name: Delete Old Releases
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}